name: 🐛 Bug Report
description: Create a report to help us improve.
title: "[🐛 Bug]: <title>"
labels: [Bug 🐛, Needs Triaging ⏳]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        First, let's get some information about the VSCode environment
        you are using. For that please open VSCode and open the `Code`
        menu and go to `About Visual Studio Code`.

  - type: input
    id: environment
    attributes:
      label: VSCode Environment
      description: Information about the VSCode environment you are using.
      placeholder: |
        Version: 1.63.2 (Universal)
        Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
        Date: 2021-12-15T09:37:28.172Z
        Electron: 13.5.2
        Chromium: 91.0.4472.164
        Node.js: 14.16.0
        V8: 9.1.269.39-electron.0
        OS: Darwin arm64 21.2.0
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Marquee Version
      description: Which version of Marquee are you running?
      placeholder: v2.0.0
    validations:
      required: true

  - type: dropdown
    id: workspace
    attributes:
      label: Workspace Type
      description: Where is your workspace located?
      options:
        - Local Workspace
        - Docker Container
        - Remote
        - Codespaces
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Describe clearly and concisely the bug including instructions showing how to reproduce it.
      placeholder: |
        Please add as many details as possible to avoid assumptions from our side. How do you
        trigger this bug? What did you expect to happen? Please walk us through it step by step.
    validations:
      required: true

  - type: textarea
    id: what-is-expected
    attributes:
      label: What is your expected behavior?
      description: |
        What did you expect to happen instead?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: |
        Please copy and paste any relevant log output generated by the Marquee
        extension. For that open the `OUTPUT` tab in the base panel and select
        Marquee in the dropdown input.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/stateful/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
